# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b511f4b923006f44f1647f9445dbeff978ae7abe72617ffb79519c434a562e3716c194f8e6c4ff86bc70e805456d6d2d3a5277a4070644b0f2569f6863a4e4b

test:
  secret_key_base: da967211e147f5a9f65534a3f995e3fe6b0e12d3ff6a94bad8ef50531963743980878f9d216c22bbf6c2a05cbd526b2007221c9f574872d4c883a76e94797000

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
